version: "3.8"

services:

  db:
    image: postgres
    container_name: tg_db
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - project3

networks:
  project3:
