FROM python:3.8.6-buster

WORKDIR /usr/src/app

ADD requirements_tg.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY ./tg_bot/ ./
COPY ./db ./db

CMD ["python3", "tg_event_handler.py"]